spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/security_study
        username: root


# MyBatis Plus配置
mybatis-plus:
    # 搜索指定包别名
    typeAliasesPackage: com.example.**.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    #  configLocation: classpath:mybatis/mybatis-config.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
